### ISSUE TITLE
Comply with image requirements

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/postgres-trunk-containers#46]
The current tag of the image for the commitfest is not compatible with CNPG:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commitfest-48-4937
spec:
  imageName: ghcr.io/gbartolini/postgresql-trunk:commitfest-48-4937
  instances: 3

  storage:
    size: 1Gi
```

Applying it returns:

```
The Cluster "commitfest-48-4937" is invalid: spec.imageName: Invalid value: "ghcr.io/gbartolini/postgresql-trunk:commitfest-48-4937": invalid version tag
```

It should contain the major version inside: `imageName: ghcr.io/gbartolini/postgresql-trunk:18-commitfest-48-4937``

Please fix this and make it consistent. Every build should start with the major.
